//Constants for getting type references
export const SURGERIES_PAGE = 'SurgeriesPage';
export const SUMMARY_PAGE = 'SummaryPage';
export const LABORATORY_PAGE = 'LaboratoryPage';
export const OFFICE_VISIS_PAGE = 'OfficeVisitsPage';
export const PROVIDERS_PAGE = 'ProvidersPage';
export const DEMOGRAPHICS_PAGE = 'DemographicsPage';
export const REGISTER_PAGE = 'RegisterPage';
export const LOGIN_PAGE = 'LoginPage';
export const SCANNER_PAGE = 'ScannerPage';
export const RECORD_LIST_PAGE = 'RecordListPage';