//Constants for getting type references
export const SUMMARY_PAGE = 'SummaryPage';
export const OFFICE_VISITS_PAGE = 'OfficeVisitsPage';
export const PROVIDERS_PAGE = 'ProvidersPage';
export const DEMOGRAPHICS_PAGE = 'DemographicsPage';
export const REGISTER_PAGE = 'RegisterPage';
export const LOGIN_PAGE = 'LoginPage';
export const SCANNER_PAGE = 'ScannerPage';
export const RECORD_LIST_PAGE = 'RecordListPage';